version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - env # my droplet hating the hidden file
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
  etl:
    image: hgmaxwellking/covid-data-dashboard-etl:latest
    env_file:
      - env
    depends_on:
      - "database"
    command: ["python3", "src/covid-data.py"]
    volumes:
      - ./data:/app/data
  www:
    image: hgmaxwellking/covid-data-dashboard-frontend:latest
    ports:
      - 80:80
    #volumes:
    #  - ./dist:/usr/share/nginx/html
  server:
    image: hgmaxwellking/covid-data-dashboard-server:latest
    env_file:
      - env # my droplet hating the hidden file
    depends_on:
      - "database"
    ports:
      - 4000:4000
volumes:
  database-data: # named volumes can be managed easier using docker-compose