/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::ByPoverty;
use diesel::prelude::*;
use diesel::dsl::Eq;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="ByPoverty"]
pub struct ByPovertyT {
    pub index: String,
    pub POVERTY_GROUP: Option<String>,
    pub CASE_RATE_ADJ: Option<f64>,
    pub HOSPITALIZED_RATE_ADJ: Option<f64>,
    pub DEATH_RATE_ADJ: Option<f64>,
    pub CASE_COUNT: Option<f64>,
    pub HOSPITALIZED_COUNT: Option<f64>,
    pub DEATH_COUNT: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<ByPovertyT> {
    ByPoverty::table
        .load::<ByPovertyT>(conn)
        .expect("Error loading object")
}
