/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::BySex;
use diesel::prelude::*;
use diesel::dsl::Eq;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="BySex"]
pub struct BySexT {
    pub index: String,
    pub SEX_GROUP: Option<String>,
    pub CASE_RATE: Option<f64>,
    pub HOSPITALIZED_RATE: Option<f64>,
    pub DEATH_RATE: Option<f64>,
    pub CASE_COUNT: Option<f64>,
    pub HOSPITALIZED_COUNT: Option<f64>,
    pub DEATH_COUNT: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<BySexT> {
    BySex::table
        .load::<BySexT>(conn)
        .expect("Error loading object")
}
