/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/
use crate::schema::AntibodyByAge;
use diesel::dsl::Eq;
use diesel::prelude::*;

#[derive(Debug, GraphQLObject, Insertable, Queryable)]
#[table_name = "AntibodyByAge"]
pub struct AntibodyByAgeT {
    pub index: i32,
    pub demo_variable: Option<String>,
    pub NUM_PEOP_TEST: Option<f64>,
    pub NUM_PEOP_POS: Option<f64>,
    pub PERCENT_POSITIVE: Option<f64>,
    pub TEST_RATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<AntibodyByAgeT> {
    AntibodyByAge::table
        .order(AntibodyByAge::date.desc())
        .load::<AntibodyByAgeT>(conn)
        .expect("Error loading object")
}
