/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::AntibodyBySex;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="AntibodyBySex"]
pub struct AntibodyBySexT {
    pub id: i32,
    pub demo_variable: Option<String>,
    pub NUM_PEOP_TEST: Option<f64>,
    pub NUM_PEOP_POS: Option<f64>,
    pub PERCENT_POSITIVE: Option<f64>,
    pub TEST_RATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<AntibodyBySexT> {
    AntibodyBySex::table
        .order(AntibodyBySex::date.asc())
        .load::<AntibodyBySexT>(conn)
        .expect("Error loading object")
}
