/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::AntibodyByModzcta;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="AntibodyByModzcta"]
pub struct AntibodyByModzctaT {
    pub id: i32,
    pub modzcta_first: Option<f64>,
    pub NEIGHBORHOOD_NAME: Option<String>,
    pub NUM_PEOP_TEST: Option<f64>,
    pub NUM_PEOP_POS: Option<f64>,
    pub PERCENT_POSITIVE: Option<f64>,
    pub TEST_RATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<AntibodyByModzctaT> {
    AntibodyByModzcta::table
        .order(AntibodyByModzcta::date.asc())
        .load::<AntibodyByModzctaT>(conn)
        .expect("Error loading object")
}
