/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::antibody-by-modzcta;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="antibody-by-modzcta"]
pub struct antibody-by-modzctaT {
    pub id: i32,
    pub modzcta_first: Option<f64>,
    pub NEIGHBORHOOD_NAME: Option<String>,
    pub NUM_PEOP_TEST: Option<f64>,
    pub NUM_PEOP_POS: Option<f64>,
    pub PERCENT_POSITIVE: Option<f64>,
    pub TEST_RATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<antibody-by-modzctaT> {
    antibody-by-modzcta::table
        .order(antibody-by-modzcta::date.asc())
        .load::<antibody-by-modzctaT>(conn)
        .expect("Error loading object")
}
