/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::by-age;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="by-age"]
pub struct by-ageT {
    pub id: i32,
    pub AGE_GROUP: Option<String>,
    pub CASE_RATE: Option<f64>,
    pub HOSPITALIZED_RATE: Option<f64>,
    pub DEATH_RATE: Option<f64>,
    pub CASE_COUNT: Option<f64>,
    pub HOSPITALIZED_COUNT: Option<f64>,
    pub DEATH_COUNT: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<by-ageT> {
    by-age::table
        .order(by-age::date.asc())
        .load::<by-ageT>(conn)
        .expect("Error loading object")
}
