/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::by-poverty;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="by-poverty"]
pub struct by-povertyT {
    pub id: i32,
    pub POVERTY_GROUP: Option<String>,
    pub CASE_RATE_ADJ: Option<f64>,
    pub HOSPITALIZED_RATE_ADJ: Option<f64>,
    pub DEATH_RATE_ADJ: Option<f64>,
    pub CASE_COUNT: Option<f64>,
    pub HOSPITALIZED_COUNT: Option<f64>,
    pub DEATH_COUNT: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<by-povertyT> {
    by-poverty::table
        .order(by-poverty::date.asc())
        .load::<by-povertyT>(conn)
        .expect("Error loading object")
}
