/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::by-sex;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="by-sex"]
pub struct by-sexT {
    pub id: i32,
    pub SEX_GROUP: Option<String>,
    pub CASE_RATE: Option<f64>,
    pub HOSPITALIZED_RATE: Option<f64>,
    pub DEATH_RATE: Option<f64>,
    pub CASE_COUNT: Option<f64>,
    pub HOSPITALIZED_COUNT: Option<f64>,
    pub DEATH_COUNT: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<by-sexT> {
    by-sex::table
        .order(by-sex::date.asc())
        .load::<by-sexT>(conn)
        .expect("Error loading object")
}
