/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::CaserateByModzctaPrime;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="CaserateByModzctaPrime"]
pub struct CaserateByModzctaPrimeT {
    pub id: i32,
    pub MODZCTA: Option<i32>,
    pub CASERATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<CaserateByModzctaPrimeT> {
    CaserateByModzctaPrime::table
        .order(CaserateByModzctaPrime::date.asc())
        .load::<CaserateByModzctaPrimeT>(conn)
        .expect("Error loading object")
}
