/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::data-by-modzcta;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="data-by-modzcta"]
pub struct data-by-modzctaT {
    pub id: i32,
    pub MODIFIED_ZCTA: Option<f64>,
    pub NEIGHBORHOOD_NAME: Option<String>,
    pub BOROUGH_GROUP: Option<String>,
    pub COVID_CASE_COUNT: Option<f64>,
    pub COVID_CASE_RATE: Option<f64>,
    pub POP_DENOMINATOR: Option<f64>,
    pub COVID_DEATH_COUNT: Option<f64>,
    pub COVID_DEATH_RATE: Option<f64>,
    pub PERCENT_POSITIVE: Option<f64>,
    pub TOTAL_COVID_TESTS: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<data-by-modzctaT> {
    data-by-modzcta::table
        .order(data-by-modzcta::date.asc())
        .load::<data-by-modzctaT>(conn)
        .expect("Error loading object")
}
