/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/
use crate::schema::DataByDay;
use diesel::prelude::*;

#[derive(Debug, GraphQLObject, Insertable, Queryable)]
#[table_name = "DataByDay"]
pub struct DataByDayT {
    pub id: i32,
    pub date_of_interest: Option<String>,
    pub CASE_COUNT: Option<i32>,
    pub PROBABLE_CASE_COUNT: Option<i32>,
    pub HOSPITALIZED_COUNT: Option<i32>,
    pub DEATH_COUNT: Option<i32>,
    pub PROBABLE_DEATH_COUNT: Option<i32>,
}

pub fn read(conn: &PgConnection) -> Vec<DataByDayT> {
    DataByDay::table
        .order(DataByDay::date_of_interest.asc())
        .load::<DataByDayT>(conn)
        .expect("Error loading object")
}
