/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::DataByModzcta;
use diesel::prelude::*;
use diesel::dsl::Eq;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="DataByModzcta"]
pub struct DataByModzctaT {
    pub index: String,
    pub MODIFIED_ZCTA: Option<f64>,
    pub NEIGHBORHOOD_NAME: Option<String>,
    pub BOROUGH_GROUP: Option<String>,
    pub COVID_CASE_COUNT: Option<f64>,
    pub COVID_CASE_RATE: Option<f64>,
    pub POP_DENOMINATOR: Option<f64>,
    pub COVID_DEATH_COUNT: Option<f64>,
    pub COVID_DEATH_RATE: Option<f64>,
    pub PERCENT_POSITIVE: Option<f64>,
    pub TOTAL_COVID_TESTS: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<DataByModzctaT> {
    DataByModzcta::table
        .load::<DataByModzctaT>(conn)
        .expect("Error loading object")
}
