/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::DeathsByUnderlyingConditions;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="DeathsByUnderlyingConditions"]
pub struct DeathsByUnderlyingConditionsT {
    pub id: i32,
    pub AGE_GROUP: Option<String>,
    pub DEATH_COUNT_TOTAL: Option<f64>,
    pub DEATH_COUNT_ILLNESS: Option<f64>,
    pub DEATH_COUNT_NO_ILLNESS: Option<f64>,
    pub DEATH_COUNT_PENDING_ILLNESS: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<DeathsByUnderlyingConditionsT> {
    DeathsByUnderlyingConditions::table
        .order(DeathsByUnderlyingConditions::date.asc())
        .load::<DeathsByUnderlyingConditionsT>(conn)
        .expect("Error loading object")
}
