/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::DeathsByRace;
use diesel::prelude::*;
use diesel::dsl::Eq;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="DeathsByRace"]
pub struct DeathsByRaceT {
    pub index: String,
    pub RACE_GROUP: Option<String>,
    pub AGE_0_17_YRS: Option<f64>,
    pub AGE_18_24_YRS: Option<f64>,
    pub AGE_25_34_YRS: Option<f64>,
    pub AGE_35_44_YRS: Option<f64>,
    pub AGE_45_54_YRS: Option<f64>,
    pub AGE_55_64_YRS: Option<f64>,
    pub AGE_65_74_YRS: Option<f64>,
    pub AGE_GE_75_YRS: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<DeathsByRaceT> {
    DeathsByRace::table
        .load::<DeathsByRaceT>(conn)
        .expect("Error loading object")
}
