/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::deaths-by-boro-age;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="deaths-by-boro-age"]
pub struct deaths-by-boro-ageT {
    pub id: i32,
    pub BOROUGH_GROUP: Option<String>,
    pub AGE_0_17_YRS: Option<f64>,
    pub AGE_18_24_YRS: Option<f64>,
    pub AGE_25_34_YRS: Option<f64>,
    pub AGE_35_44_YRS: Option<f64>,
    pub AGE_45_54_YRS: Option<f64>,
    pub AGE_55_64_YRS: Option<f64>,
    pub AGE_65_74_YRS: Option<f64>,
    pub AGE_GE_75_YRS: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<deaths-by-boro-ageT> {
    deaths-by-boro-age::table
        .order(deaths-by-boro-age::date.asc())
        .load::<deaths-by-boro-ageT>(conn)
        .expect("Error loading object")
}
