/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::group-death-by-boro;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="group-death-by-boro"]
pub struct group-death-by-boroT {
    pub id: i32,
    pub group: Option<String>,
    pub subgroup: Option<String>,
    pub BK_DEATH_COUNT: Option<f64>,
    pub BK_DEATH_RATE: Option<f64>,
    pub BX_DEATH_COUNT: Option<f64>,
    pub BX_DEATH_RATE: Option<f64>,
    pub MN_DEATH_COUNT: Option<f64>,
    pub MN_DEATH_RATE: Option<f64>,
    pub QN_DEATH_COUNT: Option<f64>,
    pub QN_DEATH_RATE: Option<f64>,
    pub SI_DEATH_COUNT: Option<f64>,
    pub SI_DEATH_RATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<group-death-by-boroT> {
    group-death-by-boro::table
        .order(group-death-by-boro::date.asc())
        .load::<group-death-by-boroT>(conn)
        .expect("Error loading object")
}
