/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::GroupDeathByBoro;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="GroupDeathByBoro"]
pub struct GroupDeathByBoroT {
    pub id: i32,
    pub group: Option<String>,
    pub subgroup: Option<String>,
    pub BK_DEATH_COUNT: Option<f64>,
    pub BK_DEATH_RATE: Option<f64>,
    pub BX_DEATH_COUNT: Option<f64>,
    pub BX_DEATH_RATE: Option<f64>,
    pub MN_DEATH_COUNT: Option<f64>,
    pub MN_DEATH_RATE: Option<f64>,
    pub QN_DEATH_COUNT: Option<f64>,
    pub QN_DEATH_RATE: Option<f64>,
    pub SI_DEATH_COUNT: Option<f64>,
    pub SI_DEATH_RATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<GroupDeathByBoroT> {
    GroupDeathByBoro::table
        .order(GroupDeathByBoro::date.asc())
        .load::<GroupDeathByBoroT>(conn)
        .expect("Error loading object")
}
