/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::GroupHospByBoro;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="GroupHospByBoro"]
pub struct GroupHospByBoroT {
    pub id: i32,
    pub group: Option<String>,
    pub subgroup: Option<String>,
    pub BK_HOSPITALIZED_COUNT: Option<f64>,
    pub BK_HOSPITALIZED_RATE: Option<f64>,
    pub BX_HOSPITALIZED_COUNT: Option<f64>,
    pub BX_HOSPITALIZED_RATE: Option<f64>,
    pub MN_HOSPITALIZED_COUNT: Option<f64>,
    pub MN_HOSPITALIZED_RATE: Option<f64>,
    pub QN_HOSPITALIZED_COUNT: Option<f64>,
    pub QN_HOSPITALIZED_RATE: Option<f64>,
    pub SI_HOSPITALIZED_COUNT: Option<f64>,
    pub SI_HOSPITALIZED_RATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<GroupHospByBoroT> {
    GroupHospByBoro::table
        .order(GroupHospByBoro::date.asc())
        .load::<GroupHospByBoroT>(conn)
        .expect("Error loading object")
}
