/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::group-hosp-by-boro;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="group-hosp-by-boro"]
pub struct group-hosp-by-boroT {
    pub id: i32,
    pub group: Option<String>,
    pub subgroup: Option<String>,
    pub BK_HOSPITALIZED_COUNT: Option<f64>,
    pub BK_HOSPITALIZED_RATE: Option<f64>,
    pub BX_HOSPITALIZED_COUNT: Option<f64>,
    pub BX_HOSPITALIZED_RATE: Option<f64>,
    pub MN_HOSPITALIZED_COUNT: Option<f64>,
    pub MN_HOSPITALIZED_RATE: Option<f64>,
    pub QN_HOSPITALIZED_COUNT: Option<f64>,
    pub QN_HOSPITALIZED_RATE: Option<f64>,
    pub SI_HOSPITALIZED_COUNT: Option<f64>,
    pub SI_HOSPITALIZED_RATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<group-hosp-by-boroT> {
    group-hosp-by-boro::table
        .order(group-hosp-by-boro::date.asc())
        .load::<group-hosp-by-boroT>(conn)
        .expect("Error loading object")
}
