/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::PercentpositiveByModzctaPrime;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="PercentpositiveByModzctaPrime"]
pub struct PercentpositiveByModzctaPrimeT {
    pub id: i32,
    pub MODZCTA: Option<i32>,
    pub PCTPOS: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<PercentpositiveByModzctaPrimeT> {
    PercentpositiveByModzctaPrime::table
        .order(PercentpositiveByModzctaPrime::date.asc())
        .load::<PercentpositiveByModzctaPrimeT>(conn)
        .expect("Error loading object")
}
