/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::ProbableConfirmedByLocation;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="ProbableConfirmedByLocation"]
pub struct ProbableConfirmedByLocationT {
    pub id: i32,
    pub LOCATION_OF_DEATH: Option<String>,
    pub CONFIRMED_DEATH: Option<f64>,
    pub PROBABLE_DEATH: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<ProbableConfirmedByLocationT> {
    ProbableConfirmedByLocation::table
        .order(ProbableConfirmedByLocation::date.asc())
        .load::<ProbableConfirmedByLocationT>(conn)
        .expect("Error loading object")
}
