/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::probable-confirmed-by-race;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="probable-confirmed-by-race"]
pub struct probable-confirmed-by-raceT {
    pub id: i32,
    pub RACE_GROUP: Option<String>,
    pub CONFIRMED_DEATH: Option<f64>,
    pub PROBABLE_DEATH: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<probable-confirmed-by-raceT> {
    probable-confirmed-by-race::table
        .order(probable-confirmed-by-race::date.asc())
        .load::<probable-confirmed-by-raceT>(conn)
        .expect("Error loading object")
}
