/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::ProbableConfirmedByBoro;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="ProbableConfirmedByBoro"]
pub struct ProbableConfirmedByBoroT {
    pub id: i32,
    pub BOROUGH_GROUP: Option<String>,
    pub CONFIRMED_DEATH: Option<f64>,
    pub PROBABLE_DEATH: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<ProbableConfirmedByBoroT> {
    ProbableConfirmedByBoro::table
        .order(ProbableConfirmedByBoro::date.asc())
        .load::<ProbableConfirmedByBoroT>(conn)
        .expect("Error loading object")
}
