/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::ProbableConfirmedByRace;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="ProbableConfirmedByRace"]
pub struct ProbableConfirmedByRaceT {
    pub id: i32,
    pub RACE_GROUP: Option<String>,
    pub CONFIRMED_DEATH: Option<f64>,
    pub PROBABLE_DEATH: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<ProbableConfirmedByRaceT> {
    ProbableConfirmedByRace::table
        .order(ProbableConfirmedByRace::date.asc())
        .load::<ProbableConfirmedByRaceT>(conn)
        .expect("Error loading object")
}
