/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::probable-confirmed-by-sex;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="probable-confirmed-by-sex"]
pub struct probable-confirmed-by-sexT {
    pub id: i32,
    pub SEX: Option<String>,
    pub CONFIRMED_DEATH: Option<f64>,
    pub PROBABLE_DEATH: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<probable-confirmed-by-sexT> {
    probable-confirmed-by-sex::table
        .order(probable-confirmed-by-sex::date.asc())
        .load::<probable-confirmed-by-sexT>(conn)
        .expect("Error loading object")
}
