/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::probable-confirmed-by-age;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="probable-confirmed-by-age"]
pub struct probable-confirmed-by-ageT {
    pub id: i32,
    pub AGE_GROUP: Option<String>,
    pub CONFIRMED_DEATH: Option<f64>,
    pub PROBABLE_DEATH: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<probable-confirmed-by-ageT> {
    probable-confirmed-by-age::table
        .order(probable-confirmed-by-age::date.asc())
        .load::<probable-confirmed-by-ageT>(conn)
        .expect("Error loading object")
}
