/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::probable-confirmed-by-boro;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="probable-confirmed-by-boro"]
pub struct probable-confirmed-by-boroT {
    pub id: i32,
    pub BOROUGH_GROUP: Option<String>,
    pub CONFIRMED_DEATH: Option<f64>,
    pub PROBABLE_DEATH: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<probable-confirmed-by-boroT> {
    probable-confirmed-by-boro::table
        .order(probable-confirmed-by-boro::date.asc())
        .load::<probable-confirmed-by-boroT>(conn)
        .expect("Error loading object")
}
