/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::Summary;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="Summary"]
pub struct SummaryT {
    pub id: i32,
    pub MEASURE: Option<String>,
    pub NUMBER_OF_NYC_RESIDENTS: Option<String>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<SummaryT> {
    Summary::table
        .order(Summary::date.asc())
        .load::<SummaryT>(conn)
        .expect("Error loading object")
}
