/**
 * {file_name}
 * This file was generated by the db-schema-generator
 *
 * Happy Hacking!
**/

use crate::schema::TestrateByModzctaPrime;
use diesel::prelude::*;


#[derive(Debug,GraphQLObject,Insertable,Queryable,)]
#[table_name="TestrateByModzctaPrime"]
pub struct TestrateByModzctaPrimeT {
    pub id: i32,
    pub MODZCTA: Option<i32>,
    pub TESTRATE: Option<f64>,
    pub date: Option<String>,
}

pub fn read(conn: &PgConnection) -> Vec<TestrateByModzctaPrimeT> {
    TestrateByModzctaPrime::table
        .order(TestrateByModzctaPrime::date.asc())
        .load::<TestrateByModzctaPrimeT>(conn)
        .expect("Error loading object")
}
