table! {
    AntibodyByAge (id) {
        id -> Int4,
        demo_variable -> Nullable<Text>,
        NUM_PEOP_TEST -> Nullable<Float8>,
        NUM_PEOP_POS -> Nullable<Float8>,
        PERCENT_POSITIVE -> Nullable<Float8>,
        TEST_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    AntibodyByBoro (id) {
        id -> Int4,
        demo_variable -> Nullable<Text>,
        NUM_PEOP_TEST -> Nullable<Float8>,
        NUM_PEOP_POS -> Nullable<Float8>,
        PERCENT_POSITIVE -> Nullable<Float8>,
        TEST_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    AntibodyByModzcta (id) {
        id -> Int4,
        modzcta_first -> Nullable<Float8>,
        NEIGHBORHOOD_NAME -> Nullable<Text>,
        NUM_PEOP_TEST -> Nullable<Float8>,
        NUM_PEOP_POS -> Nullable<Float8>,
        PERCENT_POSITIVE -> Nullable<Float8>,
        TEST_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    AntibodyByPoverty (id) {
        id -> Int4,
        demo_variable -> Nullable<Text>,
        NUM_PEOP_TEST -> Nullable<Float8>,
        NUM_PEOP_POS -> Nullable<Float8>,
        PERCENT_POSITIVE -> Nullable<Float8>,
        TEST_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    AntibodyBySex (id) {
        id -> Int4,
        demo_variable -> Nullable<Text>,
        NUM_PEOP_TEST -> Nullable<Float8>,
        NUM_PEOP_POS -> Nullable<Float8>,
        PERCENT_POSITIVE -> Nullable<Float8>,
        TEST_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    ByAge (id) {
        id -> Int4,
        AGE_GROUP -> Nullable<Text>,
        CASE_RATE -> Nullable<Float8>,
        HOSPITALIZED_RATE -> Nullable<Float8>,
        DEATH_RATE -> Nullable<Float8>,
        CASE_COUNT -> Nullable<Float8>,
        HOSPITALIZED_COUNT -> Nullable<Float8>,
        DEATH_COUNT -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    ByBoro (id) {
        id -> Int4,
        BOROUGH_GROUP -> Nullable<Text>,
        CASE_RATE -> Nullable<Float8>,
        HOSPITALIZED_RATE -> Nullable<Float8>,
        DEATH_RATE -> Nullable<Float8>,
        CASE_COUNT -> Nullable<Float8>,
        HOSPITALIZED_COUNT -> Nullable<Float8>,
        DEATH_COUNT -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    ByPoverty (id) {
        id -> Int4,
        POVERTY_GROUP -> Nullable<Text>,
        CASE_RATE_ADJ -> Nullable<Float8>,
        HOSPITALIZED_RATE_ADJ -> Nullable<Float8>,
        DEATH_RATE_ADJ -> Nullable<Float8>,
        CASE_COUNT -> Nullable<Float8>,
        HOSPITALIZED_COUNT -> Nullable<Float8>,
        DEATH_COUNT -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    ByRace (id) {
        id -> Int4,
        RACE_GROUP -> Nullable<Text>,
        CASE_RATE_ADJ -> Nullable<Float8>,
        HOSPITALIZED_RATE_ADJ -> Nullable<Float8>,
        DEATH_RATE_ADJ -> Nullable<Float8>,
        CASE_COUNT -> Nullable<Float8>,
        HOSPITALIZED_COUNT -> Nullable<Float8>,
        DEATH_COUNT -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    BySex (id) {
        id -> Int4,
        SEX_GROUP -> Nullable<Text>,
        CASE_RATE -> Nullable<Float8>,
        HOSPITALIZED_RATE -> Nullable<Float8>,
        DEATH_RATE -> Nullable<Float8>,
        CASE_COUNT -> Nullable<Float8>,
        HOSPITALIZED_COUNT -> Nullable<Float8>,
        DEATH_COUNT -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    CaserateByModzcta (id) {
        id -> Int4,
        week_ending -> Nullable<Text>,
        CASERATE_CITY -> Nullable<Float8>,
        CASERATE_BX -> Nullable<Float8>,
        CASERATE_BK -> Nullable<Float8>,
        CASERATE_MN -> Nullable<Float8>,
        CASERATE_QN -> Nullable<Float8>,
        CASERATE_SI -> Nullable<Float8>,
        CASERATE_10001 -> Nullable<Float8>,
        CASERATE_10002 -> Nullable<Float8>,
        CASERATE_10003 -> Nullable<Float8>,
        CASERATE_10004 -> Nullable<Float8>,
        CASERATE_10005 -> Nullable<Float8>,
        CASERATE_10006 -> Nullable<Float8>,
        CASERATE_10007 -> Nullable<Float8>,
        CASERATE_10009 -> Nullable<Float8>,
        CASERATE_10010 -> Nullable<Float8>,
        CASERATE_10011 -> Nullable<Float8>,
        CASERATE_10012 -> Nullable<Float8>,
        CASERATE_10013 -> Nullable<Float8>,
        CASERATE_10014 -> Nullable<Float8>,
        CASERATE_10016 -> Nullable<Float8>,
        CASERATE_10017 -> Nullable<Float8>,
        CASERATE_10018 -> Nullable<Float8>,
        CASERATE_10019 -> Nullable<Float8>,
        CASERATE_10021 -> Nullable<Float8>,
        CASERATE_10022 -> Nullable<Float8>,
        CASERATE_10023 -> Nullable<Float8>,
        CASERATE_10024 -> Nullable<Float8>,
        CASERATE_10025 -> Nullable<Float8>,
        CASERATE_10026 -> Nullable<Float8>,
        CASERATE_10027 -> Nullable<Float8>,
        CASERATE_10028 -> Nullable<Float8>,
        CASERATE_10029 -> Nullable<Float8>,
        CASERATE_10030 -> Nullable<Float8>,
        CASERATE_10031 -> Nullable<Float8>,
        CASERATE_10032 -> Nullable<Float8>,
        CASERATE_10033 -> Nullable<Float8>,
        CASERATE_10034 -> Nullable<Float8>,
        CASERATE_10035 -> Nullable<Float8>,
        CASERATE_10036 -> Nullable<Float8>,
        CASERATE_10037 -> Nullable<Float8>,
        CASERATE_10038 -> Nullable<Float8>,
        CASERATE_10039 -> Nullable<Float8>,
        CASERATE_10040 -> Nullable<Float8>,
        CASERATE_10044 -> Nullable<Float8>,
        CASERATE_10065 -> Nullable<Float8>,
        CASERATE_10069 -> Nullable<Float8>,
        CASERATE_10075 -> Nullable<Float8>,
        CASERATE_10128 -> Nullable<Float8>,
        CASERATE_10280 -> Nullable<Float8>,
        CASERATE_10282 -> Nullable<Float8>,
        CASERATE_10301 -> Nullable<Float8>,
        CASERATE_10302 -> Nullable<Float8>,
        CASERATE_10303 -> Nullable<Float8>,
        CASERATE_10304 -> Nullable<Float8>,
        CASERATE_10305 -> Nullable<Float8>,
        CASERATE_10306 -> Nullable<Float8>,
        CASERATE_10307 -> Nullable<Float8>,
        CASERATE_10308 -> Nullable<Float8>,
        CASERATE_10309 -> Nullable<Float8>,
        CASERATE_10310 -> Nullable<Float8>,
        CASERATE_10312 -> Nullable<Float8>,
        CASERATE_10314 -> Nullable<Float8>,
        CASERATE_10451 -> Nullable<Float8>,
        CASERATE_10452 -> Nullable<Float8>,
        CASERATE_10453 -> Nullable<Float8>,
        CASERATE_10454 -> Nullable<Float8>,
        CASERATE_10455 -> Nullable<Float8>,
        CASERATE_10456 -> Nullable<Float8>,
        CASERATE_10457 -> Nullable<Float8>,
        CASERATE_10458 -> Nullable<Float8>,
        CASERATE_10459 -> Nullable<Float8>,
        CASERATE_10460 -> Nullable<Float8>,
        CASERATE_10461 -> Nullable<Float8>,
        CASERATE_10462 -> Nullable<Float8>,
        CASERATE_10463 -> Nullable<Float8>,
        CASERATE_10464 -> Nullable<Float8>,
        CASERATE_10465 -> Nullable<Float8>,
        CASERATE_10466 -> Nullable<Float8>,
        CASERATE_10467 -> Nullable<Float8>,
        CASERATE_10468 -> Nullable<Float8>,
        CASERATE_10469 -> Nullable<Float8>,
        CASERATE_10470 -> Nullable<Float8>,
        CASERATE_10471 -> Nullable<Float8>,
        CASERATE_10472 -> Nullable<Float8>,
        CASERATE_10473 -> Nullable<Float8>,
        CASERATE_10474 -> Nullable<Float8>,
        CASERATE_10475 -> Nullable<Float8>,
        CASERATE_11004 -> Nullable<Float8>,
        CASERATE_11101 -> Nullable<Float8>,
        CASERATE_11102 -> Nullable<Float8>,
        CASERATE_11103 -> Nullable<Float8>,
        CASERATE_11104 -> Nullable<Float8>,
        CASERATE_11105 -> Nullable<Float8>,
        CASERATE_11106 -> Nullable<Float8>,
        CASERATE_11109 -> Nullable<Float8>,
        CASERATE_11201 -> Nullable<Float8>,
        CASERATE_11203 -> Nullable<Float8>,
        CASERATE_11204 -> Nullable<Float8>,
        CASERATE_11205 -> Nullable<Float8>,
        CASERATE_11206 -> Nullable<Float8>,
        CASERATE_11207 -> Nullable<Float8>,
        CASERATE_11208 -> Nullable<Float8>,
        CASERATE_11209 -> Nullable<Float8>,
        CASERATE_11210 -> Nullable<Float8>,
        CASERATE_11211 -> Nullable<Float8>,
        CASERATE_11212 -> Nullable<Float8>,
        CASERATE_11213 -> Nullable<Float8>,
        CASERATE_11214 -> Nullable<Float8>,
        CASERATE_11215 -> Nullable<Float8>,
        CASERATE_11216 -> Nullable<Float8>,
        CASERATE_11217 -> Nullable<Float8>,
        CASERATE_11218 -> Nullable<Float8>,
        CASERATE_11219 -> Nullable<Float8>,
        CASERATE_11220 -> Nullable<Float8>,
        CASERATE_11221 -> Nullable<Float8>,
        CASERATE_11222 -> Nullable<Float8>,
        CASERATE_11223 -> Nullable<Float8>,
        CASERATE_11224 -> Nullable<Float8>,
        CASERATE_11225 -> Nullable<Float8>,
        CASERATE_11226 -> Nullable<Float8>,
        CASERATE_11228 -> Nullable<Float8>,
        CASERATE_11229 -> Nullable<Float8>,
        CASERATE_11230 -> Nullable<Float8>,
        CASERATE_11231 -> Nullable<Float8>,
        CASERATE_11232 -> Nullable<Float8>,
        CASERATE_11233 -> Nullable<Float8>,
        CASERATE_11234 -> Nullable<Float8>,
        CASERATE_11235 -> Nullable<Float8>,
        CASERATE_11236 -> Nullable<Float8>,
        CASERATE_11237 -> Nullable<Float8>,
        CASERATE_11238 -> Nullable<Float8>,
        CASERATE_11239 -> Nullable<Float8>,
        CASERATE_11354 -> Nullable<Float8>,
        CASERATE_11355 -> Nullable<Float8>,
        CASERATE_11356 -> Nullable<Float8>,
        CASERATE_11357 -> Nullable<Float8>,
        CASERATE_11358 -> Nullable<Float8>,
        CASERATE_11360 -> Nullable<Float8>,
        CASERATE_11361 -> Nullable<Float8>,
        CASERATE_11362 -> Nullable<Float8>,
        CASERATE_11363 -> Nullable<Float8>,
        CASERATE_11364 -> Nullable<Float8>,
        CASERATE_11365 -> Nullable<Float8>,
        CASERATE_11366 -> Nullable<Float8>,
        CASERATE_11367 -> Nullable<Float8>,
        CASERATE_11368 -> Nullable<Float8>,
        CASERATE_11369 -> Nullable<Float8>,
        CASERATE_11370 -> Nullable<Float8>,
        CASERATE_11372 -> Nullable<Float8>,
        CASERATE_11373 -> Nullable<Float8>,
        CASERATE_11374 -> Nullable<Float8>,
        CASERATE_11375 -> Nullable<Float8>,
        CASERATE_11377 -> Nullable<Float8>,
        CASERATE_11378 -> Nullable<Float8>,
        CASERATE_11379 -> Nullable<Float8>,
        CASERATE_11385 -> Nullable<Float8>,
        CASERATE_11411 -> Nullable<Float8>,
        CASERATE_11412 -> Nullable<Float8>,
        CASERATE_11413 -> Nullable<Float8>,
        CASERATE_11414 -> Nullable<Float8>,
        CASERATE_11415 -> Nullable<Float8>,
        CASERATE_11416 -> Nullable<Float8>,
        CASERATE_11417 -> Nullable<Float8>,
        CASERATE_11418 -> Nullable<Float8>,
        CASERATE_11419 -> Nullable<Float8>,
        CASERATE_11420 -> Nullable<Float8>,
        CASERATE_11421 -> Nullable<Float8>,
        CASERATE_11422 -> Nullable<Float8>,
        CASERATE_11423 -> Nullable<Float8>,
        CASERATE_11426 -> Nullable<Float8>,
        CASERATE_11427 -> Nullable<Float8>,
        CASERATE_11428 -> Nullable<Float8>,
        CASERATE_11429 -> Nullable<Float8>,
        CASERATE_11432 -> Nullable<Float8>,
        CASERATE_11433 -> Nullable<Float8>,
        CASERATE_11434 -> Nullable<Float8>,
        CASERATE_11435 -> Nullable<Float8>,
        CASERATE_11436 -> Nullable<Float8>,
        CASERATE_11691 -> Nullable<Float8>,
        CASERATE_11692 -> Nullable<Float8>,
        CASERATE_11693 -> Nullable<Float8>,
        CASERATE_11694 -> Nullable<Float8>,
        CASERATE_11697 -> Nullable<Float8>,
    }
}

table! {
    CasesByDay (id) {
        id -> Int4,
        date_of_interest -> Nullable<Text>,
        CASE_COUNT -> Nullable<Int8>,
        PROBABLE_CASE_COUNT -> Nullable<Int8>,
        CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_CASE_COUNT -> Nullable<Int8>,
        BX_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        BX_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_CASE_COUNT -> Nullable<Int8>,
        BK_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        BK_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_CASE_COUNT -> Nullable<Int8>,
        MN_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        MN_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_CASE_COUNT -> Nullable<Int8>,
        QN_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        QN_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_CASE_COUNT -> Nullable<Int8>,
        SI_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        SI_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        INCOMPLETE -> Nullable<Int8>,
    }
}

table! {
    DataByDay (id) {
        id -> Int4,
        date_of_interest -> Nullable<Text>,
        CASE_COUNT -> Nullable<Int8>,
        PROBABLE_CASE_COUNT -> Nullable<Int8>,
        HOSPITALIZED_COUNT -> Nullable<Int8>,
        DEATH_COUNT -> Nullable<Int8>,
        PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        HOSP_COUNT_7DAY_AVG -> Nullable<Int8>,
        DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_CASE_COUNT -> Nullable<Int8>,
        BX_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        BX_HOSPITALIZED_COUNT -> Nullable<Int8>,
        BX_DEATH_COUNT -> Nullable<Int8>,
        BX_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        BX_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_CASE_COUNT -> Nullable<Int8>,
        BK_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        BK_HOSPITALIZED_COUNT -> Nullable<Int8>,
        BK_DEATH_COUNT -> Nullable<Int8>,
        BK_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        BK_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_CASE_COUNT -> Nullable<Int8>,
        MN_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        MN_HOSPITALIZED_COUNT -> Nullable<Int8>,
        MN_DEATH_COUNT -> Nullable<Int8>,
        MN_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        MN_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_CASE_COUNT -> Nullable<Int8>,
        QN_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        QN_HOSPITALIZED_COUNT -> Nullable<Int8>,
        QN_DEATH_COUNT -> Nullable<Int8>,
        QN_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        QN_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_CASE_COUNT -> Nullable<Int8>,
        SI_PROBABLE_CASE_COUNT -> Nullable<Int8>,
        SI_HOSPITALIZED_COUNT -> Nullable<Int8>,
        SI_DEATH_COUNT -> Nullable<Int8>,
        SI_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        SI_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_ALL_CASE_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        INCOMPLETE -> Nullable<Int8>,
    }
}

table! {
    DataByModzcta (id) {
        id -> Int4,
        MODIFIED_ZCTA -> Nullable<Float8>,
        NEIGHBORHOOD_NAME -> Nullable<Text>,
        BOROUGH_GROUP -> Nullable<Text>,
        COVID_CASE_COUNT -> Nullable<Float8>,
        COVID_CASE_RATE -> Nullable<Float8>,
        POP_DENOMINATOR -> Nullable<Float8>,
        COVID_DEATH_COUNT -> Nullable<Float8>,
        COVID_DEATH_RATE -> Nullable<Float8>,
        PERCENT_POSITIVE -> Nullable<Float8>,
        TOTAL_COVID_TESTS -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    DeathsByBoroAge (id) {
        id -> Int4,
        BOROUGH_GROUP -> Nullable<Text>,
        AGE_0_17_YRS -> Nullable<Float8>,
        AGE_18_24_YRS -> Nullable<Float8>,
        AGE_25_34_YRS -> Nullable<Float8>,
        AGE_35_44_YRS -> Nullable<Float8>,
        AGE_45_54_YRS -> Nullable<Float8>,
        AGE_55_64_YRS -> Nullable<Float8>,
        AGE_65_74_YRS -> Nullable<Float8>,
        AGE_GE_75_YRS -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    DeathsByDay (id) {
        id -> Int4,
        date_of_interest -> Nullable<Text>,
        DEATH_COUNT -> Nullable<Int8>,
        PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_DEATH_COUNT -> Nullable<Int8>,
        BX_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        BX_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_DEATH_COUNT -> Nullable<Int8>,
        BK_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        BK_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_DEATH_COUNT -> Nullable<Int8>,
        MN_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        MN_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_DEATH_COUNT -> Nullable<Int8>,
        QN_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        QN_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_DEATH_COUNT -> Nullable<Int8>,
        SI_PROBABLE_DEATH_COUNT -> Nullable<Int8>,
        SI_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_ALL_DEATH_COUNT_7DAY_AVG -> Nullable<Int8>,
        INCOMPLETE -> Nullable<Int8>,
    }
}

table! {
    DeathsByRaceAge (id) {
        id -> Int4,
        RACE_GROUP -> Nullable<Text>,
        AGE_0_17_YRS -> Nullable<Float8>,
        AGE_18_24_YRS -> Nullable<Float8>,
        AGE_25_34_YRS -> Nullable<Float8>,
        AGE_35_44_YRS -> Nullable<Float8>,
        AGE_45_54_YRS -> Nullable<Float8>,
        AGE_55_64_YRS -> Nullable<Float8>,
        AGE_65_74_YRS -> Nullable<Float8>,
        AGE_GE_75_YRS -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    DeathsByUnderlyingConditions (id) {
        id -> Int4,
        AGE_GROUP -> Nullable<Text>,
        DEATH_COUNT_TOTAL -> Nullable<Float8>,
        DEATH_COUNT_ILLNESS -> Nullable<Float8>,
        DEATH_COUNT_NO_ILLNESS -> Nullable<Float8>,
        DEATH_COUNT_PENDING_ILLNESS -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    GroupCasesByBoro (id) {
        id -> Int4,
        group -> Nullable<Text>,
        subgroup -> Nullable<Text>,
        BK_CASE_COUNT -> Nullable<Float8>,
        BK_CASE_RATE -> Nullable<Float8>,
        BX_CASE_COUNT -> Nullable<Float8>,
        BX_CASE_RATE -> Nullable<Float8>,
        MN_CASE_COUNT -> Nullable<Float8>,
        MN_CASE_RATE -> Nullable<Float8>,
        QN_CASE_COUNT -> Nullable<Float8>,
        QN_CASE_RATE -> Nullable<Float8>,
        SI_CASE_COUNT -> Nullable<Float8>,
        SI_CASE_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    GroupDataByBoro (id) {
        id -> Int4,
        group -> Nullable<Text>,
        subgroup -> Nullable<Text>,
        BK_CASE_COUNT -> Nullable<Float8>,
        BK_HOSPITALIZED_COUNT -> Nullable<Float8>,
        BK_DEATH_COUNT -> Nullable<Float8>,
        BK_CASE_RATE -> Nullable<Float8>,
        BK_HOSPITALIZED_RATE -> Nullable<Float8>,
        BK_DEATH_RATE -> Nullable<Float8>,
        BX_CASE_COUNT -> Nullable<Float8>,
        BX_HOSPITALIZED_COUNT -> Nullable<Float8>,
        BX_DEATH_COUNT -> Nullable<Float8>,
        BX_CASE_RATE -> Nullable<Float8>,
        BX_HOSPITALIZED_RATE -> Nullable<Float8>,
        BX_DEATH_RATE -> Nullable<Float8>,
        MN_CASE_COUNT -> Nullable<Float8>,
        MN_HOSPITALIZED_COUNT -> Nullable<Float8>,
        MN_DEATH_COUNT -> Nullable<Float8>,
        MN_CASE_RATE -> Nullable<Float8>,
        MN_HOSPITALIZED_RATE -> Nullable<Float8>,
        MN_DEATH_RATE -> Nullable<Float8>,
        QN_CASE_COUNT -> Nullable<Float8>,
        QN_HOSPITALIZED_COUNT -> Nullable<Float8>,
        QN_DEATH_COUNT -> Nullable<Float8>,
        QN_CASE_RATE -> Nullable<Float8>,
        QN_HOSPITALIZED_RATE -> Nullable<Float8>,
        QN_DEATH_RATE -> Nullable<Float8>,
        SI_CASE_COUNT -> Nullable<Float8>,
        SI_HOSPITALIZED_COUNT -> Nullable<Float8>,
        SI_DEATH_COUNT -> Nullable<Float8>,
        SI_CASE_RATE -> Nullable<Float8>,
        SI_HOSPITALIZED_RATE -> Nullable<Float8>,
        SI_DEATH_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    GroupDeathByBoro (id) {
        id -> Int4,
        group -> Nullable<Text>,
        subgroup -> Nullable<Text>,
        BK_DEATH_COUNT -> Nullable<Float8>,
        BK_DEATH_RATE -> Nullable<Float8>,
        BX_DEATH_COUNT -> Nullable<Float8>,
        BX_DEATH_RATE -> Nullable<Float8>,
        MN_DEATH_COUNT -> Nullable<Float8>,
        MN_DEATH_RATE -> Nullable<Float8>,
        QN_DEATH_COUNT -> Nullable<Float8>,
        QN_DEATH_RATE -> Nullable<Float8>,
        SI_DEATH_COUNT -> Nullable<Float8>,
        SI_DEATH_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    GroupHospByBoro (id) {
        id -> Int4,
        group -> Nullable<Text>,
        subgroup -> Nullable<Text>,
        BK_HOSPITALIZED_COUNT -> Nullable<Float8>,
        BK_HOSPITALIZED_RATE -> Nullable<Float8>,
        BX_HOSPITALIZED_COUNT -> Nullable<Float8>,
        BX_HOSPITALIZED_RATE -> Nullable<Float8>,
        MN_HOSPITALIZED_COUNT -> Nullable<Float8>,
        MN_HOSPITALIZED_RATE -> Nullable<Float8>,
        QN_HOSPITALIZED_COUNT -> Nullable<Float8>,
        QN_HOSPITALIZED_RATE -> Nullable<Float8>,
        SI_HOSPITALIZED_COUNT -> Nullable<Float8>,
        SI_HOSPITALIZED_RATE -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    HospByDay (id) {
        id -> Int4,
        date_of_interest -> Nullable<Text>,
        HOSPITALIZED_COUNT -> Nullable<Int8>,
        HOSP_COUNT_7DAY_AVG -> Nullable<Int8>,
        BX_HOSPITALIZED_COUNT -> Nullable<Int8>,
        BX_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        BK_HOSPITALIZED_COUNT -> Nullable<Int8>,
        BK_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        MN_HOSPITALIZED_COUNT -> Nullable<Int8>,
        MN_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        QN_HOSPITALIZED_COUNT -> Nullable<Int8>,
        QN_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        SI_HOSPITALIZED_COUNT -> Nullable<Int8>,
        SI_HOSPITALIZED_COUNT_7DAY_AVG -> Nullable<Int8>,
        INCOMPLETE -> Nullable<Int8>,
    }
}

table! {
    PercentPositiveByModzcta (id) {
        id -> Int4,
        week_ending -> Nullable<Text>,
        PCTPOS_CITY -> Nullable<Float8>,
        PCTPOS_BX -> Nullable<Float8>,
        PCTPOS_BK -> Nullable<Float8>,
        PCTPOS_MN -> Nullable<Float8>,
        PCTPOS_QN -> Nullable<Float8>,
        PCTPOS_SI -> Nullable<Float8>,
        PCTPOS_10001 -> Nullable<Float8>,
        PCTPOS_10002 -> Nullable<Float8>,
        PCTPOS_10003 -> Nullable<Float8>,
        PCTPOS_10004 -> Nullable<Float8>,
        PCTPOS_10005 -> Nullable<Float8>,
        PCTPOS_10006 -> Nullable<Float8>,
        PCTPOS_10007 -> Nullable<Float8>,
        PCTPOS_10009 -> Nullable<Float8>,
        PCTPOS_10010 -> Nullable<Float8>,
        PCTPOS_10011 -> Nullable<Float8>,
        PCTPOS_10012 -> Nullable<Float8>,
        PCTPOS_10013 -> Nullable<Float8>,
        PCTPOS_10014 -> Nullable<Float8>,
        PCTPOS_10016 -> Nullable<Float8>,
        PCTPOS_10017 -> Nullable<Float8>,
        PCTPOS_10018 -> Nullable<Float8>,
        PCTPOS_10019 -> Nullable<Float8>,
        PCTPOS_10021 -> Nullable<Float8>,
        PCTPOS_10022 -> Nullable<Float8>,
        PCTPOS_10023 -> Nullable<Float8>,
        PCTPOS_10024 -> Nullable<Float8>,
        PCTPOS_10025 -> Nullable<Float8>,
        PCTPOS_10026 -> Nullable<Float8>,
        PCTPOS_10027 -> Nullable<Float8>,
        PCTPOS_10028 -> Nullable<Float8>,
        PCTPOS_10029 -> Nullable<Float8>,
        PCTPOS_10030 -> Nullable<Float8>,
        PCTPOS_10031 -> Nullable<Float8>,
        PCTPOS_10032 -> Nullable<Float8>,
        PCTPOS_10033 -> Nullable<Float8>,
        PCTPOS_10034 -> Nullable<Float8>,
        PCTPOS_10035 -> Nullable<Float8>,
        PCTPOS_10036 -> Nullable<Float8>,
        PCTPOS_10037 -> Nullable<Float8>,
        PCTPOS_10038 -> Nullable<Float8>,
        PCTPOS_10039 -> Nullable<Float8>,
        PCTPOS_10040 -> Nullable<Float8>,
        PCTPOS_10044 -> Nullable<Float8>,
        PCTPOS_10065 -> Nullable<Float8>,
        PCTPOS_10069 -> Nullable<Float8>,
        PCTPOS_10075 -> Nullable<Float8>,
        PCTPOS_10128 -> Nullable<Float8>,
        PCTPOS_10280 -> Nullable<Float8>,
        PCTPOS_10282 -> Nullable<Float8>,
        PCTPOS_10301 -> Nullable<Float8>,
        PCTPOS_10302 -> Nullable<Float8>,
        PCTPOS_10303 -> Nullable<Float8>,
        PCTPOS_10304 -> Nullable<Float8>,
        PCTPOS_10305 -> Nullable<Float8>,
        PCTPOS_10306 -> Nullable<Float8>,
        PCTPOS_10307 -> Nullable<Float8>,
        PCTPOS_10308 -> Nullable<Float8>,
        PCTPOS_10309 -> Nullable<Float8>,
        PCTPOS_10310 -> Nullable<Float8>,
        PCTPOS_10312 -> Nullable<Float8>,
        PCTPOS_10314 -> Nullable<Float8>,
        PCTPOS_10451 -> Nullable<Float8>,
        PCTPOS_10452 -> Nullable<Float8>,
        PCTPOS_10453 -> Nullable<Float8>,
        PCTPOS_10454 -> Nullable<Float8>,
        PCTPOS_10455 -> Nullable<Float8>,
        PCTPOS_10456 -> Nullable<Float8>,
        PCTPOS_10457 -> Nullable<Float8>,
        PCTPOS_10458 -> Nullable<Float8>,
        PCTPOS_10459 -> Nullable<Float8>,
        PCTPOS_10460 -> Nullable<Float8>,
        PCTPOS_10461 -> Nullable<Float8>,
        PCTPOS_10462 -> Nullable<Float8>,
        PCTPOS_10463 -> Nullable<Float8>,
        PCTPOS_10464 -> Nullable<Float8>,
        PCTPOS_10465 -> Nullable<Float8>,
        PCTPOS_10466 -> Nullable<Float8>,
        PCTPOS_10467 -> Nullable<Float8>,
        PCTPOS_10468 -> Nullable<Float8>,
        PCTPOS_10469 -> Nullable<Float8>,
        PCTPOS_10470 -> Nullable<Float8>,
        PCTPOS_10471 -> Nullable<Float8>,
        PCTPOS_10472 -> Nullable<Float8>,
        PCTPOS_10473 -> Nullable<Float8>,
        PCTPOS_10474 -> Nullable<Float8>,
        PCTPOS_10475 -> Nullable<Float8>,
        PCTPOS_11004 -> Nullable<Float8>,
        PCTPOS_11101 -> Nullable<Float8>,
        PCTPOS_11102 -> Nullable<Float8>,
        PCTPOS_11103 -> Nullable<Float8>,
        PCTPOS_11104 -> Nullable<Float8>,
        PCTPOS_11105 -> Nullable<Float8>,
        PCTPOS_11106 -> Nullable<Float8>,
        PCTPOS_11109 -> Nullable<Float8>,
        PCTPOS_11201 -> Nullable<Float8>,
        PCTPOS_11203 -> Nullable<Float8>,
        PCTPOS_11204 -> Nullable<Float8>,
        PCTPOS_11205 -> Nullable<Float8>,
        PCTPOS_11206 -> Nullable<Float8>,
        PCTPOS_11207 -> Nullable<Float8>,
        PCTPOS_11208 -> Nullable<Float8>,
        PCTPOS_11209 -> Nullable<Float8>,
        PCTPOS_11210 -> Nullable<Float8>,
        PCTPOS_11211 -> Nullable<Float8>,
        PCTPOS_11212 -> Nullable<Float8>,
        PCTPOS_11213 -> Nullable<Float8>,
        PCTPOS_11214 -> Nullable<Float8>,
        PCTPOS_11215 -> Nullable<Float8>,
        PCTPOS_11216 -> Nullable<Float8>,
        PCTPOS_11217 -> Nullable<Float8>,
        PCTPOS_11218 -> Nullable<Float8>,
        PCTPOS_11219 -> Nullable<Float8>,
        PCTPOS_11220 -> Nullable<Float8>,
        PCTPOS_11221 -> Nullable<Float8>,
        PCTPOS_11222 -> Nullable<Float8>,
        PCTPOS_11223 -> Nullable<Float8>,
        PCTPOS_11224 -> Nullable<Float8>,
        PCTPOS_11225 -> Nullable<Float8>,
        PCTPOS_11226 -> Nullable<Float8>,
        PCTPOS_11228 -> Nullable<Float8>,
        PCTPOS_11229 -> Nullable<Float8>,
        PCTPOS_11230 -> Nullable<Float8>,
        PCTPOS_11231 -> Nullable<Float8>,
        PCTPOS_11232 -> Nullable<Float8>,
        PCTPOS_11233 -> Nullable<Float8>,
        PCTPOS_11234 -> Nullable<Float8>,
        PCTPOS_11235 -> Nullable<Float8>,
        PCTPOS_11236 -> Nullable<Float8>,
        PCTPOS_11237 -> Nullable<Float8>,
        PCTPOS_11238 -> Nullable<Float8>,
        PCTPOS_11239 -> Nullable<Float8>,
        PCTPOS_11354 -> Nullable<Float8>,
        PCTPOS_11355 -> Nullable<Float8>,
        PCTPOS_11356 -> Nullable<Float8>,
        PCTPOS_11357 -> Nullable<Float8>,
        PCTPOS_11358 -> Nullable<Float8>,
        PCTPOS_11360 -> Nullable<Float8>,
        PCTPOS_11361 -> Nullable<Float8>,
        PCTPOS_11362 -> Nullable<Float8>,
        PCTPOS_11363 -> Nullable<Float8>,
        PCTPOS_11364 -> Nullable<Float8>,
        PCTPOS_11365 -> Nullable<Float8>,
        PCTPOS_11366 -> Nullable<Float8>,
        PCTPOS_11367 -> Nullable<Float8>,
        PCTPOS_11368 -> Nullable<Float8>,
        PCTPOS_11369 -> Nullable<Float8>,
        PCTPOS_11370 -> Nullable<Float8>,
        PCTPOS_11372 -> Nullable<Float8>,
        PCTPOS_11373 -> Nullable<Float8>,
        PCTPOS_11374 -> Nullable<Float8>,
        PCTPOS_11375 -> Nullable<Float8>,
        PCTPOS_11377 -> Nullable<Float8>,
        PCTPOS_11378 -> Nullable<Float8>,
        PCTPOS_11379 -> Nullable<Float8>,
        PCTPOS_11385 -> Nullable<Float8>,
        PCTPOS_11411 -> Nullable<Float8>,
        PCTPOS_11412 -> Nullable<Float8>,
        PCTPOS_11413 -> Nullable<Float8>,
        PCTPOS_11414 -> Nullable<Float8>,
        PCTPOS_11415 -> Nullable<Float8>,
        PCTPOS_11416 -> Nullable<Float8>,
        PCTPOS_11417 -> Nullable<Float8>,
        PCTPOS_11418 -> Nullable<Float8>,
        PCTPOS_11419 -> Nullable<Float8>,
        PCTPOS_11420 -> Nullable<Float8>,
        PCTPOS_11421 -> Nullable<Float8>,
        PCTPOS_11422 -> Nullable<Float8>,
        PCTPOS_11423 -> Nullable<Float8>,
        PCTPOS_11426 -> Nullable<Float8>,
        PCTPOS_11427 -> Nullable<Float8>,
        PCTPOS_11428 -> Nullable<Float8>,
        PCTPOS_11429 -> Nullable<Float8>,
        PCTPOS_11432 -> Nullable<Float8>,
        PCTPOS_11433 -> Nullable<Float8>,
        PCTPOS_11434 -> Nullable<Float8>,
        PCTPOS_11435 -> Nullable<Float8>,
        PCTPOS_11436 -> Nullable<Float8>,
        PCTPOS_11691 -> Nullable<Float8>,
        PCTPOS_11692 -> Nullable<Float8>,
        PCTPOS_11693 -> Nullable<Float8>,
        PCTPOS_11694 -> Nullable<Float8>,
        PCTPOS_11697 -> Nullable<Float8>,
    }
}

table! {
    ProbableConfirmedByAge (id) {
        id -> Int4,
        AGE_GROUP -> Nullable<Text>,
        CONFIRMED_DEATH -> Nullable<Float8>,
        PROBABLE_DEATH -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    ProbableConfirmedByBoro (id) {
        id -> Int4,
        BOROUGH_GROUP -> Nullable<Text>,
        CONFIRMED_DEATH -> Nullable<Float8>,
        PROBABLE_DEATH -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    ProbableConfirmedByLocation (id) {
        id -> Int4,
        LOCATION_OF_DEATH -> Nullable<Text>,
        CONFIRMED_DEATH -> Nullable<Float8>,
        PROBABLE_DEATH -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    ProbableConfirmedByRace (id) {
        id -> Int4,
        RACE_GROUP -> Nullable<Text>,
        CONFIRMED_DEATH -> Nullable<Float8>,
        PROBABLE_DEATH -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    ProbableConfirmedBySex (id) {
        id -> Int4,
        SEX -> Nullable<Text>,
        CONFIRMED_DEATH -> Nullable<Float8>,
        PROBABLE_DEATH -> Nullable<Float8>,
        date -> Nullable<Text>,
    }
}

table! {
    Summary (id) {
        id -> Int4,
        MEASURE -> Nullable<Text>,
        NUMBER_OF_NYC_RESIDENTS -> Nullable<Text>,
        date -> Nullable<Text>,
    }
}

table! {
    TestrateByModzcta (id) {
        id -> Int4,
        week_ending -> Nullable<Text>,
        TESTRATE_CITY -> Nullable<Float8>,
        TESTRATE_BX -> Nullable<Float8>,
        TESTRATE_BK -> Nullable<Float8>,
        TESTRATE_MN -> Nullable<Float8>,
        TESTRATE_QN -> Nullable<Float8>,
        TESTRATE_SI -> Nullable<Float8>,
        TESTRATE_10001 -> Nullable<Float8>,
        TESTRATE_10002 -> Nullable<Float8>,
        TESTRATE_10003 -> Nullable<Float8>,
        TESTRATE_10004 -> Nullable<Float8>,
        TESTRATE_10005 -> Nullable<Float8>,
        TESTRATE_10006 -> Nullable<Float8>,
        TESTRATE_10007 -> Nullable<Float8>,
        TESTRATE_10009 -> Nullable<Float8>,
        TESTRATE_10010 -> Nullable<Float8>,
        TESTRATE_10011 -> Nullable<Float8>,
        TESTRATE_10012 -> Nullable<Float8>,
        TESTRATE_10013 -> Nullable<Float8>,
        TESTRATE_10014 -> Nullable<Float8>,
        TESTRATE_10016 -> Nullable<Float8>,
        TESTRATE_10017 -> Nullable<Float8>,
        TESTRATE_10018 -> Nullable<Float8>,
        TESTRATE_10019 -> Nullable<Float8>,
        TESTRATE_10021 -> Nullable<Float8>,
        TESTRATE_10022 -> Nullable<Float8>,
        TESTRATE_10023 -> Nullable<Float8>,
        TESTRATE_10024 -> Nullable<Float8>,
        TESTRATE_10025 -> Nullable<Float8>,
        TESTRATE_10026 -> Nullable<Float8>,
        TESTRATE_10027 -> Nullable<Float8>,
        TESTRATE_10028 -> Nullable<Float8>,
        TESTRATE_10029 -> Nullable<Float8>,
        TESTRATE_10030 -> Nullable<Float8>,
        TESTRATE_10031 -> Nullable<Float8>,
        TESTRATE_10032 -> Nullable<Float8>,
        TESTRATE_10033 -> Nullable<Float8>,
        TESTRATE_10034 -> Nullable<Float8>,
        TESTRATE_10035 -> Nullable<Float8>,
        TESTRATE_10036 -> Nullable<Float8>,
        TESTRATE_10037 -> Nullable<Float8>,
        TESTRATE_10038 -> Nullable<Float8>,
        TESTRATE_10039 -> Nullable<Float8>,
        TESTRATE_10040 -> Nullable<Float8>,
        TESTRATE_10044 -> Nullable<Float8>,
        TESTRATE_10065 -> Nullable<Float8>,
        TESTRATE_10069 -> Nullable<Float8>,
        TESTRATE_10075 -> Nullable<Float8>,
        TESTRATE_10128 -> Nullable<Float8>,
        TESTRATE_10280 -> Nullable<Float8>,
        TESTRATE_10282 -> Nullable<Float8>,
        TESTRATE_10301 -> Nullable<Float8>,
        TESTRATE_10302 -> Nullable<Float8>,
        TESTRATE_10303 -> Nullable<Float8>,
        TESTRATE_10304 -> Nullable<Float8>,
        TESTRATE_10305 -> Nullable<Float8>,
        TESTRATE_10306 -> Nullable<Float8>,
        TESTRATE_10307 -> Nullable<Float8>,
        TESTRATE_10308 -> Nullable<Float8>,
        TESTRATE_10309 -> Nullable<Float8>,
        TESTRATE_10310 -> Nullable<Float8>,
        TESTRATE_10312 -> Nullable<Float8>,
        TESTRATE_10314 -> Nullable<Float8>,
        TESTRATE_10451 -> Nullable<Float8>,
        TESTRATE_10452 -> Nullable<Float8>,
        TESTRATE_10453 -> Nullable<Float8>,
        TESTRATE_10454 -> Nullable<Float8>,
        TESTRATE_10455 -> Nullable<Float8>,
        TESTRATE_10456 -> Nullable<Float8>,
        TESTRATE_10457 -> Nullable<Float8>,
        TESTRATE_10458 -> Nullable<Float8>,
        TESTRATE_10459 -> Nullable<Float8>,
        TESTRATE_10460 -> Nullable<Float8>,
        TESTRATE_10461 -> Nullable<Float8>,
        TESTRATE_10462 -> Nullable<Float8>,
        TESTRATE_10463 -> Nullable<Float8>,
        TESTRATE_10464 -> Nullable<Float8>,
        TESTRATE_10465 -> Nullable<Float8>,
        TESTRATE_10466 -> Nullable<Float8>,
        TESTRATE_10467 -> Nullable<Float8>,
        TESTRATE_10468 -> Nullable<Float8>,
        TESTRATE_10469 -> Nullable<Float8>,
        TESTRATE_10470 -> Nullable<Float8>,
        TESTRATE_10471 -> Nullable<Float8>,
        TESTRATE_10472 -> Nullable<Float8>,
        TESTRATE_10473 -> Nullable<Float8>,
        TESTRATE_10474 -> Nullable<Float8>,
        TESTRATE_10475 -> Nullable<Float8>,
        TESTRATE_11004 -> Nullable<Float8>,
        TESTRATE_11101 -> Nullable<Float8>,
        TESTRATE_11102 -> Nullable<Float8>,
        TESTRATE_11103 -> Nullable<Float8>,
        TESTRATE_11104 -> Nullable<Float8>,
        TESTRATE_11105 -> Nullable<Float8>,
        TESTRATE_11106 -> Nullable<Float8>,
        TESTRATE_11109 -> Nullable<Float8>,
        TESTRATE_11201 -> Nullable<Float8>,
        TESTRATE_11203 -> Nullable<Float8>,
        TESTRATE_11204 -> Nullable<Float8>,
        TESTRATE_11205 -> Nullable<Float8>,
        TESTRATE_11206 -> Nullable<Float8>,
        TESTRATE_11207 -> Nullable<Float8>,
        TESTRATE_11208 -> Nullable<Float8>,
        TESTRATE_11209 -> Nullable<Float8>,
        TESTRATE_11210 -> Nullable<Float8>,
        TESTRATE_11211 -> Nullable<Float8>,
        TESTRATE_11212 -> Nullable<Float8>,
        TESTRATE_11213 -> Nullable<Float8>,
        TESTRATE_11214 -> Nullable<Float8>,
        TESTRATE_11215 -> Nullable<Float8>,
        TESTRATE_11216 -> Nullable<Float8>,
        TESTRATE_11217 -> Nullable<Float8>,
        TESTRATE_11218 -> Nullable<Float8>,
        TESTRATE_11219 -> Nullable<Float8>,
        TESTRATE_11220 -> Nullable<Float8>,
        TESTRATE_11221 -> Nullable<Float8>,
        TESTRATE_11222 -> Nullable<Float8>,
        TESTRATE_11223 -> Nullable<Float8>,
        TESTRATE_11224 -> Nullable<Float8>,
        TESTRATE_11225 -> Nullable<Float8>,
        TESTRATE_11226 -> Nullable<Float8>,
        TESTRATE_11228 -> Nullable<Float8>,
        TESTRATE_11229 -> Nullable<Float8>,
        TESTRATE_11230 -> Nullable<Float8>,
        TESTRATE_11231 -> Nullable<Float8>,
        TESTRATE_11232 -> Nullable<Float8>,
        TESTRATE_11233 -> Nullable<Float8>,
        TESTRATE_11234 -> Nullable<Float8>,
        TESTRATE_11235 -> Nullable<Float8>,
        TESTRATE_11236 -> Nullable<Float8>,
        TESTRATE_11237 -> Nullable<Float8>,
        TESTRATE_11238 -> Nullable<Float8>,
        TESTRATE_11239 -> Nullable<Float8>,
        TESTRATE_11354 -> Nullable<Float8>,
        TESTRATE_11355 -> Nullable<Float8>,
        TESTRATE_11356 -> Nullable<Float8>,
        TESTRATE_11357 -> Nullable<Float8>,
        TESTRATE_11358 -> Nullable<Float8>,
        TESTRATE_11360 -> Nullable<Float8>,
        TESTRATE_11361 -> Nullable<Float8>,
        TESTRATE_11362 -> Nullable<Float8>,
        TESTRATE_11363 -> Nullable<Float8>,
        TESTRATE_11364 -> Nullable<Float8>,
        TESTRATE_11365 -> Nullable<Float8>,
        TESTRATE_11366 -> Nullable<Float8>,
        TESTRATE_11367 -> Nullable<Float8>,
        TESTRATE_11368 -> Nullable<Float8>,
        TESTRATE_11369 -> Nullable<Float8>,
        TESTRATE_11370 -> Nullable<Float8>,
        TESTRATE_11372 -> Nullable<Float8>,
        TESTRATE_11373 -> Nullable<Float8>,
        TESTRATE_11374 -> Nullable<Float8>,
        TESTRATE_11375 -> Nullable<Float8>,
        TESTRATE_11377 -> Nullable<Float8>,
        TESTRATE_11378 -> Nullable<Float8>,
        TESTRATE_11379 -> Nullable<Float8>,
        TESTRATE_11385 -> Nullable<Float8>,
        TESTRATE_11411 -> Nullable<Float8>,
        TESTRATE_11412 -> Nullable<Float8>,
        TESTRATE_11413 -> Nullable<Float8>,
        TESTRATE_11414 -> Nullable<Float8>,
        TESTRATE_11415 -> Nullable<Float8>,
        TESTRATE_11416 -> Nullable<Float8>,
        TESTRATE_11417 -> Nullable<Float8>,
        TESTRATE_11418 -> Nullable<Float8>,
        TESTRATE_11419 -> Nullable<Float8>,
        TESTRATE_11420 -> Nullable<Float8>,
        TESTRATE_11421 -> Nullable<Float8>,
        TESTRATE_11422 -> Nullable<Float8>,
        TESTRATE_11423 -> Nullable<Float8>,
        TESTRATE_11426 -> Nullable<Float8>,
        TESTRATE_11427 -> Nullable<Float8>,
        TESTRATE_11428 -> Nullable<Float8>,
        TESTRATE_11429 -> Nullable<Float8>,
        TESTRATE_11432 -> Nullable<Float8>,
        TESTRATE_11433 -> Nullable<Float8>,
        TESTRATE_11434 -> Nullable<Float8>,
        TESTRATE_11435 -> Nullable<Float8>,
        TESTRATE_11436 -> Nullable<Float8>,
        TESTRATE_11691 -> Nullable<Float8>,
        TESTRATE_11692 -> Nullable<Float8>,
        TESTRATE_11693 -> Nullable<Float8>,
        TESTRATE_11694 -> Nullable<Float8>,
        TESTRATE_11697 -> Nullable<Float8>,
    }
}

table! {
    ZctaToModzcta (index) {
        index -> Int8,
        ZCTA -> Nullable<Int8>,
        MODZCTA -> Nullable<Int8>,
    }
}

allow_tables_to_appear_in_same_query!(
    AntibodyByAge,
    AntibodyByBoro,
    AntibodyByModzcta,
    AntibodyByPoverty,
    AntibodyBySex,
    ByAge,
    ByBoro,
    ByPoverty,
    ByRace,
    BySex,
    CaserateByModzcta,
    CasesByDay,
    DataByDay,
    DataByModzcta,
    DeathsByBoroAge,
    DeathsByDay,
    DeathsByRaceAge,
    DeathsByUnderlyingConditions,
    GroupCasesByBoro,
    GroupDataByBoro,
    GroupDeathByBoro,
    GroupHospByBoro,
    HospByDay,
    PercentPositiveByModzcta,
    ProbableConfirmedByAge,
    ProbableConfirmedByBoro,
    ProbableConfirmedByLocation,
    ProbableConfirmedByRace,
    ProbableConfirmedBySex,
    Summary,
    TestrateByModzcta,
    ZctaToModzcta,
);
